name: Deploy to Google Cloud Functions

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run: echo "Checked out $(git branch --show-current) at $(git log -1 --format=%H)"

      - name: Authenticate Google Cloud CLI
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set PATH explicitly
        run: echo "/opt/hostedtoolcache/gcloud/472.0.0/x64/bin:$PATH" >> $GITHUB_ENV
        
      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'  # Consider specifying a stable version known to work locally

      - name: Print running script content
        run: cat $RUNNER_WORKSPACE/_temp/*.sh

      - name: Log gcloud version
        run: gcloud --version

      - name: Set Google Cloud Project
        run: |
          echo ${{ secrets.GCP_SA_KEY }} | gcloud auth activate-service-account --key-file=-
          gcloud config set project ${{ secrets.GCP_PROJECT }}

      - run: gcloud config list project
        name: Log current project

      - name: Deploy to Google Cloud Functions
        run: gcloud builds submit --config cloudbuild.yaml

      - name: Diagnose deployment
        if: failure()  # This step will run only if the previous step fails
        run: |
          echo "Deployment failed. Diagnostic information:"
          echo "Checking authenticated accounts..."
          gcloud auth list
          echo "Showing recent projects..."
          gcloud projects list
          echo "Detailed gcloud info:"
          gcloud info
