name: Deploy to Google Cloud Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v2.1.0
        with:
          version: 'latest'  # This refers to the Google Cloud SDK version

      - name: Authenticate Google Cloud CLI
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to Google Cloud Functions
        run: |
          gcloud builds submit --config cloudbuild.yaml
