name: Deploy 2 Google Cloud Functions

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Google Cloud
        uses: google-github-actions/setup-gcloud@vlatest
        with:
          version: 'latest'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Deploy to Google Cloud Functions
        run: |
          gcloud builds submit --config cloudbuild.yaml
